language: php

matrix:
  include:
    # PHP tests
    - language: php
      php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit
    - language: php
      php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit
    - language: php
      php: 7.1
      env: COMPOSER_FLAGS=""
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit
    - language: php
      php: 7.1
      env: SYMFONY_VERSION="4.0.*"
      before_script:
        - composer update $COMPOSER_FLAGS --prefer-dist
      script: vendor/bin/phpunit
