language: php

env:
  global:
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    # PHP tests
    - language: php
      php: 7.2
    - language: php
      php: 7.3
      env: COMPOSER_FLAGS=""
    - language: php
      php: 7.3
      env: SYMFONY_VERSION="4.0.*"
    - language: php
      php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - composer update $COMPOSER_FLAGS --prefer-dist

script:
  - vendor/bin/phpunit

